version: 2

sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: product
        identifier: raw_gz_product
        columns:
          - name: products_id
          - name: purchase_price
      - name: sales
        identifier: raw_gz_sales
        columns:
          - name: date_date
          - name: orders_id
          - name: products_id
          - name: revenue
          - name: quantity
      - name: ship
        identifier: raw_gz_ship
        columns:
          - name: orders_id
          - name: shipping_fee
          - name: shipping_fee_1
          - name: logCost
          - name: ship_cost
